    export const SET_CALCULATION_TYPES  = 'SET_CALCULATION_TYPES';
    // export const SET_SERVICE  = 'SET_SERVICE';
    // export const SET_SERVICE_INSURANCE_DETAILS  = 'SET_SERVICE_INSURANCE_DETAILS';