    export const SET_SUBSCRIBERS  = 'SET_SUBSCRIBERS';
    export const SET_SUBSCRIBER  = 'SET_SUBSCRIBER';
    export const ADD_SUBSCRIBER  = 'ADD_SUBSCRIBER';
    export const ADD_SUBSCRIBER_EPISODE  = 'ADD_SUBSCRIBER_EPISODE';
    export const DELETE_SUBSCRIPTION  = 'DELETE_SUBSCRIPTION';
