    export const SET_SERVICE_PROVIDERS  = 'SET_SERVICE_PROVIDERS';
    export const SET_SERVICE_PROVIDER  = 'SET_SERVICE_PROVIDER';
    export const UPDATE_SERVICE_PROVIDERS  = 'UPDATE_SERVICE_PROVIDERS';
    export const ADD_SERVICE_PROVIDER  = 'ADD_SERVICE_PROVIDER';
    export const REMOVE_SERVICE_PROVIDER  = 'REMOVE_SERVICE_PROVIDER';
    
    // export const SET_SERVICE  = 'SET_SERVICE';
    // export const SET_SERVICE_INSURANCE_DETAILS  = 'SET_SERVICE_INSURANCE_DETAILS';